### ISSUE TITLE
com.github.kaklakariada.fritzbox.mapping.DeserializerException: Error parsing response body

### ISSUE THREAD

**Issue by WolfgangFahl** [kaklakariada/fritzbox-java-api#8]
When there is a repeater in the network the deserializer does not work anymore.

**Comment by Pitillo** [comment]
The Problem is that this library is only for the SmartHome devices. I had the same Error with the AVM FRITZ!DECT 300. For these I've edited the Library so you can also use them and don't get the error. If you could provide the full stacktrace, i could try to change the library, so you can use the library for repeaters to.

**Comment by WolfgangFahl** [comment]
https://github.com/WolfgangFahl/fritzbox-java-api/commit/e07c3486f8ec4b3b46e8ed17e6aee885836e7f6e lines 46 to 50 have the fix  - some xmlelements are not valid for repeaters

**Comment by Pitillo** [comment]
If you would provide the full StackTrace i coul add features to comunicate with repeaters. Unfortunately I don't have any repeaters in my network, so i can't write the needed classes. I could try to add the needed classes using the documentation by AVM. When I'm complete you could try to use the library with the new features.

**Comment by kaklakariada** [comment]
Thanks to @WolfgangFahl, I implemented the changes from https://github.com/WolfgangFahl/fritzbox-java-api/commit/e07c3486f8ec4b3b46e8ed17e6aee885836e7f6e.
